
services:

  db:
    container_name: maria-db
    image: mariadb:11.2-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3308:3306
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8083:8080